In [1]:
#Consider the below code to answer further questions:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

* Ans_1. Yes, there is a difference in the data type of the variables list_ and array_list. The variable list_ is a Python list, while array_list is a NumPy array.

In [2]:
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [3]:
#Ans_2.
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

print("Data types of elements in list_:")
for i in list_:
    print(type(i))
    
print("\nData types of elements in array_list:")
for i in array_list:
    print(type(i))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
* array_list = np.array(object = list_, dtype = int)
* Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_and array_list.

In [4]:
#Ans_3.
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_, dtype = int)

print("Data types of elements in list_:")
for i in list_:
    print(type(i))
    
print("\nData types of elements in array_list:")
for i in array_list:
    print(type(i))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [5]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
* (i) shape
* (ii) size

In [6]:
#Ans_4.
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

shape = num_array.shape
print("Shape of num_array:", shape)

size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
* [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [7]:
#Ans_5.
zeros_matrix = np.zeros((3,3))
shape = zeros_matrix.shape
print("Shape of zeros_matrix:", shape)
size = zeros_matrix.size
print("Size of zeros_matrix:", size)
print(zeros_matrix)

Shape of zeros_matrix: (3, 3)
Size of zeros_matrix: 9
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
* [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
#Ans_6.
identity_matrix = np.eye(5)

In [9]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])